const getPlanInformatica = () => {
  return [
    {
      nro: 1,
      cuatrimestre: 1,
      nombre: "Matemática Básica",
      cht: 90,
      regularizadas_para_cursar: [0],
      aprobadas_para_cursar: [0],
    },
    {
      nro: 2,
      cuatrimestre: 1,
      nombre: "Fundamentos de Programación",
      cht: 90,
      regularizadas_para_cursar: [0],
      aprobadas_para_cursar: [0],
    },
    {
      nro: 3,
      cuatrimestre: 1,
      nombre: "Química General",
      cht: 60,
      regularizadas_para_cursar: [0],
      aprobadas_para_cursar: [0],
    },
    {
      nro: 4,
      cuatrimestre: 1,
      nombre: "Comunicación Técnica I",
      cht: 60,
      regularizadas_para_cursar: [0],
      aprobadas_para_cursar: [0],
    },
    {
      nro: 5,
      cuatrimestre: 2,
      nombre: "Álgebra Lineal",
      cht: 75,
      regularizadas_para_cursar: [1],
      aprobadas_para_cursar: [0],
    },
    {
      nro: 6,
      cuatrimestre: 2,
      nombre: "Cálculo I",
      cht: 75,
      regularizadas_para_cursar: [1],
      aprobadas_para_cursar: [0],
    },
    {
      nro: 7,
      cuatrimestre: 2,
      nombre: "Programación Orientada a Objetos",
      cht: 90,
      regularizadas_para_cursar: [2],
      aprobadas_para_cursar: [0],
    },
    {
      nro: 8,
      cuatrimestre: 2,
      nombre: "Comunicación Técnica II",
      cht: 60,
      regularizadas_para_cursar: [4],
      aprobadas_para_cursar: [0],
    },
    {
      nro: 9,
      cuatrimestre: 3,
      nombre: "Física I",
      cht: 120,
      regularizadas_para_cursar: [6],
      aprobadas_para_cursar: [0],
    },
    {
      nro: 10,
      cuatrimestre: 3,
      nombre: "Cálculo II",
      cht: 90,
      regularizadas_para_cursar: [6],
      aprobadas_para_cursar: [0],
    },
    {
      nro: 11,
      cuatrimestre: 3,
      nombre: "Teoría de la Computación",
      cht: 105,
      regularizadas_para_cursar: [1, 2, 3, 4, 5, 6, 7],
      aprobadas_para_cursar: [0],
    },
    {
      nro: 12,
      cuatrimestre: 3,
      nombre: "Ingeniería de Software I",
      cht: 90,
      regularizadas_para_cursar: [7],
      aprobadas_para_cursar: [0],
    },
    {
      nro: 13,
      cuatrimestre: 4,
      nombre: "Física II",
      cht: 105,
      regularizadas_para_cursar: [9],
      aprobadas_para_cursar: [1, 2, 3, 4],
    },
    {
      nro: 14,
      cuatrimestre: 4,
      nombre: "Ecuaciones Diferenciales",
      cht: 75,
      regularizadas_para_cursar: [10],
      aprobadas_para_cursar: [1, 2, 3, 4],
    },
    {
      nro: 15,
      cuatrimestre: 4,
      nombre: "Algoritmos y Estructuras de Datos",
      cht: 90,
      regularizadas_para_cursar: [11],
      aprobadas_para_cursar: [1, 2, 3, 4],
    },
    {
      nro: 16,
      cuatrimestre: 4,
      nombre: "Ingeniería de Software II",
      cht: 90,
      regularizadas_para_cursar: [12],
      aprobadas_para_cursar: [1, 2, 3, 4],
    },
    {
      nro: 17,
      cuatrimestre: 5,
      nombre: "Electrónica Digital",
      cht: 90,
      regularizadas_para_cursar: [13],
      aprobadas_para_cursar: [1, 2, 3, 4, 5, 6, 7, 8],
    },
    {
      nro: 18,
      cuatrimestre: 5,
      nombre: "Tecnologías de la Programación",
      cht: 90,
      regularizadas_para_cursar: [15],
      aprobadas_para_cursar: [1, 2, 3, 4, 5, 6, 7, 8],
    },
    {
      nro: 19,
      cuatrimestre: 5,
      nombre: "Estadística",
      cht: 90,
      regularizadas_para_cursar: [10],
      aprobadas_para_cursar: [1, 2, 3, 4, 5, 6, 7, 8],
    },
    {
      nro: 20,
      cuatrimestre: 5,
      nombre: "Cálculo Numérico",
      cht: 90,
      regularizadas_para_cursar: [14],
      aprobadas_para_cursar: [1, 2, 3, 4, 5, 6, 7, 8],
    },
    {
      nro: 21,
      cuatrimestre: 6,
      nombre: "Computación Gráfica ",
      cht: 105,
      regularizadas_para_cursar: [0],
      aprobadas_para_cursar: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    },
    {
      nro: 22,
      cuatrimestre: 6,
      nombre: "Bases de Datos",
      cht: 90,
      regularizadas_para_cursar: [16],
      aprobadas_para_cursar: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    },
    {
      nro: 23,
      cuatrimestre: 6,
      nombre: "Organización de Computadoras",
      cht: 90,
      regularizadas_para_cursar: [17],
      aprobadas_para_cursar: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    },
    {
      nro: 24,
      cuatrimestre: 6,
      nombre: "Ciencia, Tecnología y Sociedad",
      cht: 75,
      regularizadas_para_cursar: [0],
      aprobadas_para_cursar: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    },
    {
      nro: 25,
      cuatrimestre: 7,
      nombre: "Sistemas Operativos",
      cht: 90,
      regularizadas_para_cursar: [23],
      aprobadas_para_cursar: [5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16],
    },
    {
      nro: 26,
      cuatrimestre: 7,
      nombre: "Administración de Proyectos de Software",
      cht: 90,
      regularizadas_para_cursar: [22],
      aprobadas_para_cursar: [5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16],
    },
    {
      nro: 27,
      cuatrimestre: 7,
      nombre: "Procesamiento Digital de Señales",
      cht: 90,
      regularizadas_para_cursar: [0],
      aprobadas_para_cursar: [5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16],
    },
    {
      nro: 28,
      cuatrimestre: 7,
      nombre: "Mecánica del Continuo",
      cht: 90,
      regularizadas_para_cursar: [0],
      aprobadas_para_cursar: [5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16],
    },
    {
      nro: 29,
      cuatrimestre: 8,
      nombre: "Redes y Comunicaciones de Datos I",
      cht: 90,
      regularizadas_para_cursar: [23],
      aprobadas_para_cursar: [9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
    },
    {
      nro: 30,
      cuatrimestre: 8,
      nombre: "Mecánica Computacional",
      cht: 105,
      regularizadas_para_cursar: [28],
      aprobadas_para_cursar: [9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
    },
    {
      nro: 31,
      cuatrimestre: 8,
      nombre: "Inteligencia Computacional",
      cht: 90,
      regularizadas_para_cursar: [0],
      aprobadas_para_cursar: [9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
    },
    {
      nro: 32,
      cuatrimestre: 9,
      nombre: "Procesamiento Digital de Imágenes",
      cht: 105,
      regularizadas_para_cursar: [27],
      aprobadas_para_cursar: [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24],
    },
    {
      nro: 33,
      cuatrimestre: 9,
      nombre: "Redes y Comunicación de Datos II",
      cht: 105,
      regularizadas_para_cursar: [29],
      aprobadas_para_cursar: [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24],
    },
    {
      nro: 34,
      cuatrimestre: 9,
      nombre: "Economía y Costos",
      cht: 60,
      regularizadas_para_cursar: [0],
      aprobadas_para_cursar: [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24],
    },
    {
      nro: 35,
      cuatrimestre: 10,
      nombre: "Auditoría Informática",
      cht: 90,
      regularizadas_para_cursar: [0],
      aprobadas_para_cursar: [17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28],
    },
    {
      nro: 36,
      cuatrimestre: 10,
      nombre: "Gestión de Empresas",
      cht: 60,
      regularizadas_para_cursar: [0],
      aprobadas_para_cursar: [17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28],
    },
  ];
};

//TODO completar todas las materias
const getPlanRecursosHidricos = () => {
  return [
    {
      nro: 1,
      cuatrimestre: 1,
      nombre: "Matemática Básica",
      cht: 90,
      regularizadas_para_cursar: [0],
      aprobadas_para_cursar: [0],
    },
    {
      nro: 2,
      cuatrimestre: 1,
      nombre: "Química General e Inorgánica",
      cht: 105,
      regularizadas_para_cursar: [0],
      aprobadas_para_cursar: [0],
    },
    {
      nro: 3,
      cuatrimestre: 1,
      nombre: "Comunicación Técnica I",
      cht: 60,
      regularizadas_para_cursar: [0],
      aprobadas_para_cursar: [0],
    },
    {
      nro: 4,
      cuatrimestre: 2,
      nombre: "Álgebra Lineal",
      cht: 75,
      regularizadas_para_cursar: [1],
      aprobadas_para_cursar: [0],
    },
    {
      nro: 5,
      cuatrimestre: 2,
      nombre: "Cálculo I",
      cht: 75,
      regularizadas_para_cursar: [1],
      aprobadas_para_cursar: [0],
    },
    {
      nro: 6,
      cuatrimestre: 2,
      nombre: "Comunicación Técnica II",
      cht: 60,
      regularizadas_para_cursar: [3],
      aprobadas_para_cursar: [0],
    },
    {
      nro: 7,
      cuatrimestre: 2,
      nombre: "Química y Biología del Agua",
      cht: 90,
      regularizadas_para_cursar: [2],
      aprobadas_para_cursar: [0],
    },
    {
      nro: 8,
      cuatrimestre: 3,
      nombre: "Física I",
      cht: 120,
      regularizadas_para_cursar: [5],
      aprobadas_para_cursar: [0],
    },
    {
      nro: 9,
      cuatrimestre: 3,
      nombre: "Cálculo II",
      cht: 90,
      regularizadas_para_cursar: [5],
      aprobadas_para_cursar: [0],
    },
    {
      nro: 10,
      cuatrimestre: 3,
      nombre: "Tecnología, Ambiente y Sociedad",
      cht: 75,
      regularizadas_para_cursar: [0],
      aprobadas_para_cursar: [0],
    },
    {
      nro: 11,
      cuatrimestre: 3,
      nombre: "Elementos de Cartografía y Topografía ",
      cht: 45,
      regularizadas_para_cursar: [3],
      aprobadas_para_cursar: [0],
    },

    {
      nro: 12,
      cuatrimestre: 4,
      nombre: "Física II",
      cht: 105,
      regularizadas_para_cursar: [8],
      aprobadas_para_cursar: [1, 2, 3],
    },
    {
      nro: 13,
      cuatrimestre: 4,
      nombre: "Ecuaciones Diferenciales",
      cht: 75,
      regularizadas_para_cursar: [9],
      aprobadas_para_cursar: [1, 2, 3],
    },
    {
      nro: 14,
      cuatrimestre: 4,
      nombre: "Estadística",
      cht: 90,
      regularizadas_para_cursar: [9],
      aprobadas_para_cursar: [1, 2, 3],
    },
    {
      nro: 15,
      cuatrimestre: 4,
      nombre: "Geología, Geomorfología y Suelos",
      cht: 90,
      regularizadas_para_cursar: [11],
      aprobadas_para_cursar: [1, 2, 3],
    },
    {
      nro: 16,
      cuatrimestre: 5,
      nombre: "Mecánica de Fluidos",
      cht: 105,
      regularizadas_para_cursar: [0],
      aprobadas_para_cursar: [1, 2, 3, 4, 5, 6, 7],
    },
    {
      nro: 17,
      cuatrimestre: 5,
      nombre: "Teoría de Estructuras I",
      cht: 105,
      regularizadas_para_cursar: [8],
      aprobadas_para_cursar: [1, 2, 3, 4, 5, 6, 7],
    },
    {
      nro: 18,
      cuatrimestre: 5,
      nombre: "Hidrometeorología",
      cht: 90,
      regularizadas_para_cursar: [14],
      aprobadas_para_cursar: [1, 2, 3, 4, 5, 6, 7],
    },
    {
      nro: 19,
      cuatrimestre: 5,
      nombre: "Topografía e Hidrometría",
      cht: 60,
      regularizadas_para_cursar: [11],
      aprobadas_para_cursar: [1, 2, 3, 4, 5, 6, 7],
    },
    {
      nro: 20,
      cuatrimestre: 7,
      nombre: "Métodos Numéricos y Computación",
      cht: 90,
      regularizadas_para_cursar: [0],
      aprobadas_para_cursar: [
        1,
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        9,
        10,
        11,
        12,
        13,
        14,
        15,
      ],
    },
    {
      nro: 21,
      cuatrimestre: 6,
      nombre: "Hidráulica de Canales",
      cht: 90,
      regularizadas_para_cursar: [16],
      aprobadas_para_cursar: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
    },
    {
      nro: 22,
      cuatrimestre: 6,
      nombre: "Teoría de Estructuras II",
      cht: 90,
      regularizadas_para_cursar: [17],
      aprobadas_para_cursar: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
    },
    {
      nro: 23,
      cuatrimestre: 7,
      nombre: "Hidrología de Superficie",
      cht: 90,
      regularizadas_para_cursar: [18],
      aprobadas_para_cursar: [
        1,
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        9,
        10,
        11,
        12,
        13,
        14,
        15,
      ],
    },
    {
      nro: 24,
      cuatrimestre: 7,
      nombre: "Legislación del Agua",
      cht: 60,
      regularizadas_para_cursar: [0],
      aprobadas_para_cursar: [
        1,
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        9,
        10,
        11,
        12,
        13,
        14,
        15,
      ],
    },
    {
      nro: 25,
      cuatrimestre: 6,
      nombre: "Mecánica de Suelos e Ingeniería Geotécnica",
      cht: 90,
      regularizadas_para_cursar: [0],
      aprobadas_para_cursar: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
    },
    {
      nro: 26,
      cuatrimestre: 7,
      nombre: "Hormigón Armado",
      cht: 90,
      regularizadas_para_cursar: [0],
      aprobadas_para_cursar: [
        1,
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        9,
        10,
        11,
        12,
        13,
        14,
        15,
      ],
    },
    {
      nro: 27,
      cuatrimestre: 7,
      nombre: "Economía y Costos",
      cht: 60,
      regularizadas_para_cursar: [0],
      aprobadas_para_cursar: [
        1,
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        9,
        10,
        11,
        12,
        13,
        14,
        15,
      ],
    },
    {
      nro: 28,
      cuatrimestre: 8,
      nombre: "Hidrología Subterránea",
      cht: 75,
      regularizadas_para_cursar: [0],
      aprobadas_para_cursar: [
        1,
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        9,
        10,
        11,
        12,
        13,
        14,
        15,
        16,
        17,
        18,
        19,
      ],
    },
    {
      nro: 29,
      cuatrimestre: 8,
      nombre: "Obras Hidráulicas I",
      cht: 90,
      regularizadas_para_cursar: [21],
      aprobadas_para_cursar: [
        1,
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        9,
        10,
        11,
        12,
        13,
        14,
        15,
        16,
        17,
        18,
        19,
      ],
    },
    {
      nro: 30,
      cuatrimestre: 8,
      nombre: "Hidráulica Fluvial",
      cht: 90,
      regularizadas_para_cursar: [21],
      aprobadas_para_cursar: [
        1,
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        9,
        10,
        11,
        12,
        13,
        14,
        15,
        16,
        17,
        18,
        19,
      ],
    },
    {
      nro: 31,
      cuatrimestre: 8,
      nombre: "Diseño Estructural de Obras Hidráulicas",
      cht: 75,
      regularizadas_para_cursar: [26],
      aprobadas_para_cursar: [
        1,
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        9,
        10,
        11,
        12,
        13,
        14,
        15,
        16,
        17,
        18,
        19,
      ],
    },
    {
      nro: 32,
      cuatrimestre: 9,
      nombre: "Aprovechamiento de Aguas Subterráneas",
      cht: 75,
      regularizadas_para_cursar: [28],
      aprobadas_para_cursar: [
        1,
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        9,
        10,
        11,
        12,
        13,
        14,
        15,
        16,
        17,
        18,
        19,
        21,
        22,
        25,
      ],
    },
    {
      nro: 33,
      cuatrimestre: 9,
      nombre: "Obras Hidráulicas II",
      cht: 90,
      regularizadas_para_cursar: [29],
      aprobadas_para_cursar: [
        1,
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        9,
        10,
        11,
        12,
        13,
        14,
        15,
        16,
        17,
        18,
        19,
        21,
        22,
        25,
      ],
    },
    {
      nro: 34,
      cuatrimestre: 9,
      nombre: "Gestión Integrada de Recursos Hídricos",
      cht: 75,
      regularizadas_para_cursar: [23],
      aprobadas_para_cursar: [
        1,
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        9,
        10,
        11,
        12,
        13,
        14,
        15,
        16,
        17,
        18,
        19,
        21,
        22,
        25,
      ],
    },
    {
      nro: 35,
      cuatrimestre: 9,
      nombre: "Riego y Drenaje",
      cht: 75,
      regularizadas_para_cursar: [28],
      aprobadas_para_cursar: [
        1,
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        9,
        10,
        11,
        12,
        13,
        14,
        15,
        16,
        17,
        18,
        19,
        21,
        22,
        25,
      ],
    },
    {
      nro: 36,
      cuatrimestre: 10,
      nombre: "Ingeniería Sanitaria",
      cht: 90,
      regularizadas_para_cursar: [29, 30, 31, 32],
      aprobadas_para_cursar: [
        1,
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        9,
        10,
        11,
        12,
        13,
        14,
        15,
        16,
        17,
        18,
        19,
        20,
        21,
        22,
        23,
        24,
        25,
        26,
        27,
      ],
    },
    {
      nro: 37,
      cuatrimestre: 10,
      nombre: "Programación y Gestión de Obras",
      cht: 75,
      regularizadas_para_cursar: [33],
      aprobadas_para_cursar: [
        1,
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        9,
        10,
        11,
        12,
        13,
        14,
        15,
        16,
        17,
        18,
        19,
        20,
        21,
        22,
        23,
        24,
        25,
        26,
        27,
      ],
    },
    {
      nro: 38,
      cuatrimestre: 10,
      nombre: "Formulación y Evaluación Económico Ambiental de Proyectos ",
      cht: 60,
      regularizadas_para_cursar: [31],
      aprobadas_para_cursar: [
        1,
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        9,
        10,
        11,
        12,
        13,
        14,
        15,
        16,
        17,
        18,
        19,
        20,
        21,
        22,
        23,
        24,
        25,
        26,
        27,
      ],
    },
  ];
};

const getPlanAmbiental = () => {
  return [
    {
      nro: 1,
      cuatrimestre: 1,
      nombre: "Matemática Básica",
      cht: 90,
      regularizadas_para_cursar: [0],
      aprobadas_para_cursar: [0],
    },
    {
      nro: 2,
      cuatrimestre: 1,
      nombre: "Química General e Inorgánica",
      cht: 105,
      regularizadas_para_cursar: [0],
      aprobadas_para_cursar: [0],
    },
    {
      nro: 3,
      cuatrimestre: 1,
      nombre: "Comunicación Técnica I",
      cht: 60,
      regularizadas_para_cursar: [0],
      aprobadas_para_cursar: [0],
    },
    {
      nro: 4,
      cuatrimestre: 2,
      nombre: "Álgebra Lineal",
      cht: 75,
      regularizadas_para_cursar: [1],
      aprobadas_para_cursar: [0],
    },
    {
      nro: 5,
      cuatrimestre: 2,
      nombre: "Cálculo I",
      cht: 75,
      regularizadas_para_cursar: [1],
      aprobadas_para_cursar: [0],
    },
    {
      nro: 6,
      cuatrimestre: 2,
      nombre: "Comunicación Técnica II",
      cht: 60,
      regularizadas_para_cursar: [3],
      aprobadas_para_cursar: [0],
    },
    {
      nro: 7,
      cuatrimestre: 2,
      nombre: "Química Ambiental I",
      cht: 105,
      regularizadas_para_cursar: [2],
      aprobadas_para_cursar: [0],
    },
    {
      nro: 8,
      cuatrimestre: 3,
      nombre: "Física I",
      cht: 120,
      regularizadas_para_cursar: [5],
      aprobadas_para_cursar: [0],
    },
    {
      nro: 9,
      cuatrimestre: 3,
      nombre: "Cálculo II",
      cht: 90,
      regularizadas_para_cursar: [5],
      aprobadas_para_cursar: [0],
    },
    {
      nro: 10,
      cuatrimestre: 3,
      nombre: "Tecnología, Ambiente y Sociedad",
      cht: 75,
      regularizadas_para_cursar: [0],
      aprobadas_para_cursar: [0],
    },
    {
      nro: 11,
      cuatrimestre: 3,
      nombre: "Elementos de Cartografía y Topografía ",
      cht: 45,
      regularizadas_para_cursar: [3],
      aprobadas_para_cursar: [0],
    },
    {
      nro: 12,
      cuatrimestre: 3,
      nombre: "- Química Ambiental II Ingeniería de Software I",
      cht: 90,
      regularizadas_para_cursar: [7],
      aprobadas_para_cursar: [0],
    },
    {
      nro: 13,
      cuatrimestre: 4,
      nombre: "Física II",
      cht: 105,
      regularizadas_para_cursar: [8],
      aprobadas_para_cursar: [1, 2, 3],
    },
    {
      nro: 14,
      cuatrimestre: 4,
      nombre: "Ecuaciones Diferenciales",
      cht: 75,
      regularizadas_para_cursar: [9],
      aprobadas_para_cursar: [1, 2, 3],
    },
    {
      nro: 15,
      cuatrimestre: 4,
      nombre: "Estadística",
      cht: 90,
      regularizadas_para_cursar: [9],
      aprobadas_para_cursar: [1, 2, 3],
    },
    {
      nro: 16,
      cuatrimestre: 4,
      nombre: "Geología, Geomorfología y Suelos",
      cht: 90,
      regularizadas_para_cursar: [11],
      aprobadas_para_cursar: [1, 2, 3],
    },
    {
      nro: 17,
      cuatrimestre: 5,
      nombre: "Mecánica de Fluidos",
      cht: 105,
      regularizadas_para_cursar: [0],
      aprobadas_para_cursar: [1, 2, 3, 4, 5, 6, 7],
    },
    {
      nro: 18,
      cuatrimestre: 6,
      nombre: "Fisicoquímica y Transporte en Suelos ",
      cht: 75,
      regularizadas_para_cursar: [17],
      aprobadas_para_cursar: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    },
    {
      nro: 19,
      cuatrimestre: 5,
      nombre: "Fisicoquímica",
      cht: 120,
      regularizadas_para_cursar: [0],
      aprobadas_para_cursar: [1, 2, 3, 4, 5, 6, 7],
    },
    {
      nro: 20,
      cuatrimestre: 5,
      nombre: "Microbiología Ambiental",
      cht: 120,
      regularizadas_para_cursar: [12],
      aprobadas_para_cursar: [1, 2, 3, 4, 5, 6, 7],
    },
    {
      nro: 21,
      cuatrimestre: 5,
      nombre: "Métodos Numéricos y Computación",
      cht: 90,
      regularizadas_para_cursar: [0],
      aprobadas_para_cursar: [1, 2, 3, 4, 5, 6, 7],
    },
    {
      nro: 22,
      cuatrimestre: 6,
      nombre: "Hidráulica Aplicada",
      cht: 105,
      regularizadas_para_cursar: [17],
      aprobadas_para_cursar: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    },
    {
      nro: 23,
      cuatrimestre: 6,
      nombre: "Hidrología Aplicada",
      cht: 105,
      regularizadas_para_cursar: [0],
      aprobadas_para_cursar: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    },
    {
      nro: 24,
      cuatrimestre: 6,
      nombre: "Ecología",
      cht: 90,
      regularizadas_para_cursar: [12],
      aprobadas_para_cursar: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    },
    {
      nro: 25,
      cuatrimestre: 7,
      nombre: "Procesos Fisicoquímicos en Ingeniería Ambiental",
      cht: 120,
      regularizadas_para_cursar: [0],
      aprobadas_para_cursar: [5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16],
    },
    {
      nro: 26,
      cuatrimestre: 7,
      nombre: "Contaminación Atmosférica",
      cht: 105,
      regularizadas_para_cursar: [0],
      aprobadas_para_cursar: [5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16],
    },
    {
      nro: 27,
      cuatrimestre: 7,
      nombre: "Modelación Ambiental",
      cht: 120,
      regularizadas_para_cursar: [0],
      aprobadas_para_cursar: [5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16],
    },
    {
      nro: 28,
      cuatrimestre: 8,
      nombre: " Procesos Biológicos en Ingeniería Ambiental",
      cht: 120,
      regularizadas_para_cursar: [0],
      aprobadas_para_cursar: [
        5,
        6,
        7,
        8,
        9,
        10,
        11,
        12,
        13,
        14,
        15,
        16,
        17,
        19,
        20,
      ],
    },
    {
      nro: 29,
      cuatrimestre: 8,
      nombre: "- Gestión Integrada de Recursos Naturales",
      cht: 90,
      regularizadas_para_cursar: [27],
      aprobadas_para_cursar: [9, 10, 11, 12, 13, 14, 15, 16, 17, 19, 20],
    },
    {
      nro: 30,
      cuatrimestre: 9,
      nombre: "Residuos Sólidos",
      cht: 105,
      regularizadas_para_cursar: [0],
      aprobadas_para_cursar: [
        9,
        10,
        11,
        12,
        13,
        14,
        15,
        16,
        17,
        18,
        19,
        20,
        21,
        22,
        23,
        24,
      ],
    },
    {
      nro: 31,
      cuatrimestre: 9,
      nombre: "Economía y Costos",
      cht: 60,
      regularizadas_para_cursar: [0],
      aprobadas_para_cursar: [
        9,
        10,
        11,
        12,
        13,
        14,
        15,
        16,
        17,
        18,
        19,
        20,
        21,
        22,
        23,
        24,
      ],
    },
    {
      nro: 32,
      cuatrimestre: 9,
      nombre: "Diseño de Sistemas Ambientales",
      cht: 120,
      regularizadas_para_cursar: [0],
      aprobadas_para_cursar: [
        9,
        10,
        11,
        12,
        13,
        14,
        15,
        16,
        17,
        18,
        19,
        20,
        21,
        22,
        23,
        24,
      ],
    },
    {
      nro: 33,
      cuatrimestre: 10,
      nombre: "Análisis de Riesgo y Legislación Ambiental",
      cht: 90,
      regularizadas_para_cursar: [0],
      aprobadas_para_cursar: [
        13,
        14,
        15,
        16,
        17,
        18,
        19,
        20,
        21,
        22,
        23,
        24,
        25,
        26,
        27,
      ],
    },
    {
      nro: 34,
      cuatrimestre: 10,
      nombre: "Formulación y Evaluación Económico Ambiental de Proyectos",
      cht: 60,
      regularizadas_para_cursar: [31],
      aprobadas_para_cursar: [
        13,
        14,
        15,
        16,
        17,
        18,
        19,
        20,
        21,
        22,
        23,
        24,
        25,
        26,
        27,
      ],
    },
  ];
};

const getPlanAgrimensura = () => {
  return [
    {
      nro: 1,
      cuatrimestre: 1,
      nombre: "Matemática Básica",
      cht: 90,
      regularizadas_para_cursar: [0],
      aprobadas_para_cursar: [0],
    },
    {
      nro: 2,
      cuatrimestre: 3,
      nombre: "Ciencia, Tecnología y Sociedad",
      cht: 60,
      regularizadas_para_cursar: [0],
      aprobadas_para_cursar: [0],
    },
    {
      nro: 3,
      cuatrimestre: 1,
      nombre: " Topografía General",
      cht: 90,
      regularizadas_para_cursar: [0],
      aprobadas_para_cursar: [0],
    },
    {
      nro: 3.1,
      cuatrimestre: 2,
      nombre: "Topografía General (Cont.)",
      cht: 90,
      regularizadas_para_cursar: [0],
      aprobadas_para_cursar: [0],
    },
    {
      nro: 4,
      cuatrimestre: 1,
      nombre: "Comunicación Técnica I",
      cht: 60,
      regularizadas_para_cursar: [0],
      aprobadas_para_cursar: [0],
    },
    {
      nro: 4.1,
      cuatrimestre: 2,
      nombre: "Comunicación Técnica (Cont.)",
      cht: 60,
      regularizadas_para_cursar: [0],
      aprobadas_para_cursar: [0],
    },
    {
      nro: 5,
      cuatrimestre: 2,
      nombre: "Álgebra Lineal",
      cht: 75,
      regularizadas_para_cursar: [1],
      aprobadas_para_cursar: [0],
    },
    {
      nro: 6,
      cuatrimestre: 4,
      nombre: "Introducción a la Cartografía",
      cht: 90,
      regularizadas_para_cursar: [0],
      aprobadas_para_cursar: [1, 10, 3, 4, 4.1],
    },
    {
      nro: 7,
      cuatrimestre: 2,
      nombre: "Cálculo y Geometría Analítica",
      cht: 105,
      regularizadas_para_cursar: [1],
      aprobadas_para_cursar: [0],
    },
    {
      nro: 8,
      cuatrimestre: 3,
      nombre: "Física I",
      cht: 120,
      regularizadas_para_cursar: [7],
      aprobadas_para_cursar: [0],
    },
    {
      nro: 9,
      cuatrimestre: 3,
      nombre: "Topografía Aplicada I",
      cht: 90,
      regularizadas_para_cursar: [3, 3.1],
      aprobadas_para_cursar: [0],
    },
    {
      nro: 10,
      cuatrimestre: 1,
      nombre: "Química General",
      cht: 60,
      regularizadas_para_cursar: [0],
      aprobadas_para_cursar: [0],
    },
    {
      nro: 11,
      cuatrimestre: 3,
      nombre: "Cálculo y Métodos Numéricos",
      cht: 120,
      regularizadas_para_cursar: [7],
      aprobadas_para_cursar: [0],
    },
    {
      nro: 12,
      cuatrimestre: 4,
      nombre: "Física II",
      cht: 105,
      regularizadas_para_cursar: [8],
      aprobadas_para_cursar: [1, 10, 3, 3.1, 4, 4.1],
    },
    {
      nro: 13,
      cuatrimestre: 4,
      nombre: "Topografía Aplicada II",
      cht: 90,
      regularizadas_para_cursar: [9],
      aprobadas_para_cursar: [1, 10, 3, 3.1, 4, 4.1],
    },
    {
      nro: 14,
      cuatrimestre: 4,
      nombre: "Estadística",
      cht: 90,
      regularizadas_para_cursar: [7],
      aprobadas_para_cursar: [1, 10, 3, 3.1, 4, 4.1],
    },
    {
      nro: 15,
      cuatrimestre: 5,
      nombre: "Geomorfología",
      cht: 75,
      regularizadas_para_cursar: [0],
      aprobadas_para_cursar: [1, 10, 3, 3.1, 4, 4.1, 5, 7],
    },
    {
      nro: 16,
      cuatrimestre: 5,
      nombre: "Fotogrametría",
      cht: 105,
      regularizadas_para_cursar: [0],
      aprobadas_para_cursar: [1, 10, 3, 3.1, 4, 4.1, 5, 7],
    },
    {
      nro: 17,
      cuatrimestre: 5,
      nombre: "Agrimensura Legal I",
      cht: 75,
      regularizadas_para_cursar: [0],
      aprobadas_para_cursar: [1, 10, 3, 3.1, 4, 4.1, 5, 7],
    },
    {
      nro: 18,
      cuatrimestre: 5,
      nombre: "Teorías de Errores",
      cht: 75,
      regularizadas_para_cursar: [11, 12, 13, 14],
      aprobadas_para_cursar: [1, 10, 3, 3.1, 4, 4.1, 5, 7],
    },
    {
      nro: 19,
      cuatrimestre: 6,
      nombre: "Introducción a la Informática y a los SIG",
      cht: 90,
      regularizadas_para_cursar: [0],
      aprobadas_para_cursar: [1, 2, 9, 8, 10, 11, 3, 3.1, 4, 4.1, 5, 7],
    },
    {
      nro: 20,
      cuatrimestre: 6,
      nombre: "Geodesia",
      cht: 105,
      regularizadas_para_cursar: [0],
      aprobadas_para_cursar: [1, 2, 9, 8, 10, 11, 3, 3.1, 4, 4.1, 5, 7],
    },
    {
      nro: 21,
      cuatrimestre: 6,
      nombre: "Agrimensura Legal II",
      cht: 75,
      regularizadas_para_cursar: [17],
      aprobadas_para_cursar: [1, 2, 9, 8, 10, 11, 3, 3.1, 4, 4.1, 5, 7],
    },
    {
      nro: 22,
      cuatrimestre: 6,
      nombre: "Geografía Física",
      cht: 75,
      regularizadas_para_cursar: [0],
      aprobadas_para_cursar: [1, 2, 9, 8, 10, 11, 3, 3.1, 4, 4.1, 5, 7],
    },
    {
      nro: 23,
      cuatrimestre: 7,
      nombre: "Interpretación de Imágenes",
      cht: 90,
      regularizadas_para_cursar: [16],
      aprobadas_para_cursar: [
        1,
        2,
        9,
        8,
        10,
        11,
        3,
        3.1,
        4,
        4.1,
        5,
        7,
        6,
        12,
        13,
        14,
      ],
    },
    {
      nro: 24,
      cuatrimestre: 7,
      nombre: "Economía y Costos",
      cht: 60,
      regularizadas_para_cursar: [0],
      aprobadas_para_cursar: [
        1,
        2,
        9,
        8,
        10,
        11,
        3,
        3.1,
        4,
        4.1,
        5,
        7,
        6,
        12,
        13,
        14,
      ],
    },
    {
      nro: 25,
      cuatrimestre: 7,
      nombre: "Representaciones Cartográficas",
      cht: 90,
      regularizadas_para_cursar: [20],
      aprobadas_para_cursar: [
        1,
        2,
        9,
        8,
        10,
        11,
        3,
        3.1,
        4,
        4.1,
        5,
        7,
        6,
        12,
        13,
        14,
      ],
    },
    {
      nro: 26,
      cuatrimestre: 7,
      nombre: "Mensura",
      cht: 105,
      regularizadas_para_cursar: [21],
      aprobadas_para_cursar: [
        1,
        2,
        9,
        8,
        10,
        11,
        3,
        3.1,
        4,
        4.1,
        5,
        7,
        6,
        12,
        13,
        14,
      ],
    },
    {
      nro: 27,
      cuatrimestre: 8,
      nombre: "Teledetección",
      cht: 90,
      regularizadas_para_cursar: [23],
      aprobadas_para_cursar: [
        1,
        2,
        9,
        8,
        10,
        11,
        3,
        3.1,
        4,
        4.1,
        5,
        7,
        6,
        12,
        13,
        14,
        15,
        16,
        17,
        18,
      ],
    },
    {
      nro: 28,
      cuatrimestre: 8,
      nombre: "Sistemas de Información Geográfica I",
      cht: 90,
      regularizadas_para_cursar: [19],
      aprobadas_para_cursar: [
        1,
        2,
        9,
        8,
        10,
        11,
        3,
        3.1,
        4,
        4.1,
        5,
        7,
        6,
        12,
        13,
        14,
        15,
        16,
        17,
        18,
      ],
    },
    {
      nro: 29,
      cuatrimestre: 8,
      nombre: "Catastro",
      cht: 120,
      regularizadas_para_cursar: [26],
      aprobadas_para_cursar: [
        1,
        2,
        9,
        8,
        10,
        11,
        3,
        3.1,
        4,
        4.1,
        5,
        7,
        6,
        12,
        13,
        14,
        15,
        16,
        17,
        18,
      ],
    },
    {
      nro: 30,
      cuatrimestre: 8,
      nombre: "Cartografía Temática",
      cht: 90,
      regularizadas_para_cursar: [25],
      aprobadas_para_cursar: [
        1,
        2,
        9,
        8,
        10,
        11,
        3,
        3.1,
        4,
        4.1,
        5,
        7,
        6,
        12,
        13,
        14,
        15,
        16,
        17,
        18,
      ],
    },
    {
      nro: 31,
      cuatrimestre: 9,
      nombre: "Ordenamiento Territorial",
      cht: 90,
      regularizadas_para_cursar: [28],
      aprobadas_para_cursar: [
        1,
        2,
        9,
        8,
        10,
        11,
        3,
        3.1,
        4,
        4.1,
        5,
        7,
        6,
        12,
        13,
        14,
        15,
        16,
        17,
        18,
        19,
        20,
        21,
        22,
      ],
    },
    {
      nro: 32,
      cuatrimestre: 9,
      nombre: "Estudios y Trazados Especiales",
      cht: 105,
      regularizadas_para_cursar: [0],
      aprobadas_para_cursar: [
        1,
        2,
        9,
        8,
        10,
        11,
        3,
        3.1,
        4,
        4.1,
        5,
        7,
        6,
        12,
        13,
        14,
        15,
        16,
        17,
        18,
        19,
        20,
        21,
        22,
      ],
    },
    {
      nro: 33,
      cuatrimestre: 10,
      nombre: "Valuación Inmobiliaria",
      cht: 90,
      regularizadas_para_cursar: [0],
      aprobadas_para_cursar: [
        1,
        2,
        9,
        8,
        10,
        11,
        3,
        3.1,
        4,
        4.1,
        5,
        7,
        6,
        12,
        13,
        14,
        15,
        16,
        17,
        18,
        19,
        20,
        21,
        22,
        23,
        24,
        25,
        26,
      ],
    },
  ];
};
